refactor dsply -> noti + add mac apps

diff --git a/dots/.scripts/noti b/dots/.scripts/noti
--- a/dots/.scripts/noti
+++ b/dots/.scripts/noti
@@ -2,12 +2,12 @@
 # shellcheck disable=2220
 set -Eeuo pipefail
 
-# dsply - Shows a notification depending on what OS you are
-# $ dsply [OPTIONS] [COMMAND]
+# noti - Shows a notification depending on what OS you are
+# $ noti [OPTIONS] [COMMAND]
 
 # USAGE:
-#   $ dsply echo "Hello notification"
-#   $ sleep 3 && dsply -t"Sleeping" -m"sshhh"
+#   $ noti echo "Hello notification"
+#   $ sleep 3 && noti -t"Sleeping" -m"sshhh"
 
 # OPTIONS:
 #   -t      Sets the title of the notification
@@ -16,29 +16,28 @@ set -Eeuo pipefail
 
 # COMMAND:
 #   Runs the command and then display information on finish example:
-#   $ dsply echo "hello"
+#   $ noti echo "hello"
 #   # hello (and display the notification)
 
 TITLE="Title"
 BODY="Hello"
 
-mac(){
+mac() {
     osascript -e "display notification \"$BODY\" \
         with title \"$TITLE\" ${SOUND:-}"
 }
 
-tmux_dsply(){
+tmux_noti() {
     tmux display "$TITLE: $BODY"
 }
 
 # Parse options
-while getopts ":bt:m:" OPT
-do
-  case $OPT in
-      t) TITLE="$OPTARG" ;;
-      m) BODY="$OPTARG" ;;
-      b) SOUND="sound name \"Submarine\"" ;;
-  esac
+while getopts ":bt:m:" OPT; do
+    case $OPT in
+    t) TITLE="$OPTARG" ;;
+    m) BODY="$OPTARG" ;;
+    b) SOUND="sound name \"Submarine\"" ;;
+    esac
 done
 shift $((OPTIND - 1))
 
@@ -48,18 +47,16 @@ if [ ${#@} -gt 0 ]; then
 fi
 
 case "$(uname -s)" in
-    [Dd]arwin)
-        eval "$@"
-        mac
-        ;;
-    *)
-        if [[ "$TMUX" ]]
-        then
-            eval "$@" || true
-            tmux_dsply
-        else
-            echo "'$0' Cannot be used at this time ¯\\_(ツ)_/¯"
-        fi
-        ;;
+[Dd]arwin)
+    eval "$@"
+    mac
+    ;;
+*)
+    if [[ "$TMUX" ]]; then
+        eval "$@" || true
+        tmux_noti
+    else
+        echo "'$0' Cannot be used at this time ¯\\_(ツ)_/¯"
+    fi
+    ;;
 esac
-
